using System;
using DVLD.Core.DTOs.Enums;
using DVLD.Core.Exceptions;

namespace DVLD.Core.DTOs.Entities
{
    public class License
    {
        private int _licenseId;
        private int _applicationId;
        private int _driverId;
        private LicenseClass _licenseClass;
        private DateTime _issueDate;
        private DateTime _expirationDate;
        private string _notes;
        private decimal _paidFees;
        private bool _isActive;
        private IssueReason _issueReason;
        private int _createdByUserId;


        public int LicenseID
        {
            get => _licenseId;
            private set
            {
                if (value <= 0)
                    throw new ValidationException("LicenseId must be a positive integer.");
                _licenseId = value;
            }
        }

        public int ApplicationId
        {
            get => _applicationId;
            set
            {
                if (value <= 0)
                    throw new ValidationException("ApplicationId must be a positive integer.");
                _applicationId = value;
            }
        }

        public int DriverId
        {
            get => _driverId;
            set
            {
                if (value <= 0)
                    throw new ValidationException("DriveId must be a positive integer.");
                _driverId = value;
            }
        }

        public LicenseClass LicenseClass
        {
            get => _licenseClass;
            set => _licenseClass = value;
        }

        public DateTime IssueDate
        {
            get => _issueDate;
            private set
            {
                if (value > DateTime.Now)
                    throw new ValidationException("IssueDate cannot be in the future.");
                _issueDate = value;
            }
        }

        public DateTime ExpirationDate
        {
            get => _expirationDate;
            private set
            {
                if (value <= IssueDate)
                    throw new ValidationException("ExpirationDate must be after IssueDate.");
                _expirationDate = value;
            }
        }

        public string Notes
        {
            get => _notes;
            
            set
            {
                if (value != null && value.Length > 500)
                    throw new ValidationException("Notes cannot exceed 500 characters.");
                _notes = value;
            }
        }

        public decimal PaidFees
        {
            get => _paidFees;
            set
            {
                if (value < 0)
                    throw new ValidationException("PaidFees cannot be negative.");
                _paidFees = value;
            }
        }

        public bool IsActive
        {
            get => _isActive;
            private set => _isActive = value;
        }

        public IssueReason IssueReason
        {
            get => _issueReason;
            private set => _issueReason = value;
        }

        public int CreatedByUserId
        {
            get => _createdByUserId;
            private set
            {
                if (value <= 0)
                    throw new ValidationException("CreatedByUserId must be a positive integer.");
                _createdByUserId = value;
            }
        }


        public License()
        {
            // Set default values for all fields across private fields directly
            _licenseId = -1;
            _applicationId = -1;
            _driverId = -1;
            _licenseClass = LicenseClass.Class1_SmallMotorcycle;
            _issueDate = DateTime.MinValue;
            _expirationDate = DateTime.MinValue;
            _notes = null;
            _paidFees = 0;
            _isActive = false;
            _issueReason = IssueReason.FirstTime;
            _createdByUserId = -1;
        }

        // Constructor for sending data to DAL when creating a new license (LicenseId is auto-generated by the database).
        public License(int applicationId, int driverId, LicenseClass licenseClass, string notes, decimal paidFees) : this()
        {
            ApplicationId = applicationId;
            DriverId = driverId;
            LicenseClass = licenseClass;
            Notes = notes;
            PaidFees = paidFees;
        }

        // Constructor for receiving data from DAL when retrieving a license (LicenseId is included).
        internal License(int licenseId, int applicationId, int driverId, LicenseClass licenseClass, DateTime issueDate, DateTime expirationDate, string notes, decimal paidFees, bool isActive, IssueReason issueReason, int createdByUserId) : this()
        {
            LicenseID = licenseId;
            ApplicationId = applicationId;
            DriverId = driverId;
            LicenseClass = licenseClass;
            IssueDate = issueDate;
            ExpirationDate = expirationDate;
            Notes = notes;
            PaidFees = paidFees;
            IsActive = isActive;
            IssueReason = issueReason;
            CreatedByUserId = createdByUserId;
        }
    }
}
